In [64]:
import pandas as pd
df=pd.read_csv("employee.csv")

In [65]:
df.head(20)

,email_id,subject,body,sender_email,sender_domain,claimed_company,company_domain,domain_match,free_or_third_party_domain,has_link,has_attachment,mentions_money,mentions_urgency,mentions_personal_info,job_offer_without_interview,label
0,1,Remote Job Offer – Machine Learning Engineer,We reviewed your profile and would like you to...,careers.salesforce@outlook.com,outlook.com,Salesforce,salesforce.com,0,1,1,0,0,1,1,0,1
1,2,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.cisco@gmail.com,gmail.com,Cisco,cisco.com,0,1,0,0,0,1,1,1,1
2,3,Remote Job Offer – Data Scientist,We reviewed your profile and would like you to...,careers.google@gmail.com,gmail.com,Google,google.com,0,1,1,0,0,1,1,0,1
3,4,Invitation to Interview and Assessment – Data ...,Your application has been approved. Kindly pro...,recruiting.kpmg@outlook.com,outlook.com,KPMG,kpmg.com,0,1,0,0,0,1,1,1,1
4,5,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.tesla@secure-offer-letter.com,secure-offer-letter.com,Tesla,tesla.com,0,1,0,0,0,1,1,1,1
5,6,Assessment Test Required – AI Operations Gener...,Congratulations. You have been selected for a ...,recruitment.team@recruit-portal-mail.com,recruit-portal-mail.com,Microsoft,microsoft.com,0,1,0,0,0,1,0,1,1
6,7,Invitation to Interview and Assessment – Platf...,Your application has been approved. Kindly pro...,hiring.jobs-apple@recruit-portal-mail.com,recruit-portal-mail.com,Apple,apple.com,0,1,0,0,0,1,1,1,1
7,8,Assessment Test Required – Cloud Data Engineer,Congratulations. You have been selected for a ...,careers.amazon@hire-now-careers.com,hire-now-careers.com,Amazon,amazon.jobs,0,1,0,0,0,1,0,1,1
8,9,Assessment Test Required – Data Analyst,We reviewed your profile and would like you to...,assessment.coordinator@gmail.com,gmail.com,KPMG,kpmg.com,0,1,1,0,0,1,1,0,1
9,10,Remote Job Offer – Platform Engineer,"We offer competitive pay, sign-on bonus, train...",assessment.coordinator@talent-onboard-now.com,talent-onboard-now.com,JPMorgan Chase,jpmorgan.com,0,1,0,1,1,1,0,0,1
10,11,Application Update – Software Engineer,Congratulations. You have been selected for a ...,careers.cisco@gmail.com,gmail.com,Cisco,cisco.com,0,1,0,0,0,1,0,1,1
11,12,Assessment Test Required – Software Engineer,"To secure your position, confirm your interest...",assessment.coordinator@hire-now-careers.com,hire-now-careers.com,Pfizer,pfizer.com,0,1,0,0,1,0,1,0,1
12,13,Invitation to Interview and Assessment – Cloud...,We reviewed your profile and would like you to...,hiring.jobs-adobe@secure-offer-letter.com,secure-offer-letter.com,Adobe,adobe.com,0,1,1,0,0,1,1,0,1
13,14,Application Update – Business Analyst,"To secure your position, confirm your interest...",hrinfo.uber@secure-offer-letter.com,secure-offer-letter.com,Uber,uber.com,0,1,0,0,1,0,1,0,1
14,15,Offer Confirmation – Data Analyst,Your application has been approved. Kindly pro...,hr.department@hire-now-careers.com,hire-now-careers.com,JPMorgan Chase,jpmorgan.com,0,1,0,0,0,1,1,1,1
15,16,Assessment Test Required – Business Analyst,"To secure your position, confirm your interest...",careers.goldmansachs@talent-onboard-now.com,talent-onboard-now.com,Goldman Sachs,goldmansachs.com,0,1,0,0,1,0,1,0,1
16,17,Immediate Hiring – Data Analyst,"To secure your position, confirm your interest...",hrinfo.stripe@outlook.com,outlook.com,Stripe,stripe.com,0,1,0,0,1,0,1,0,1
17,18,Final Selection Notice – Software Engineer,Your application has been approved. Kindly pro...,talent.paypal@talent-onboard-now.com,talent-onboard-now.com,PayPal,paypal.com,0,1,0,0,0,1,1,1,1
18,19,Final Selection Notice – Data Scientist,"We offer competitive pay, sign-on bonus, train...",assessment.coordinator@viazohorecruit.com,viazohorecruit.com,Goldman Sachs,goldmansachs.com,0,1,0,1,1,1,0,0,1
19,20,Assessment Test Required – Machine Learning En...,We reviewed your profile and would like you to...,hrinfo.cisco@talent-onboard-now.com,talent-onboard-now.com,Cisco,cisco.com,0,1,1,0,0,1,1,0,1

In [66]:
df_X = df.drop(columns=["label"])

In [67]:
df_X

,email_id,subject,body,sender_email,sender_domain,claimed_company,company_domain,domain_match,free_or_third_party_domain,has_link,has_attachment,mentions_money,mentions_urgency,mentions_personal_info,job_offer_without_interview
0,1,Remote Job Offer – Machine Learning Engineer,We reviewed your profile and would like you to...,careers.salesforce@outlook.com,outlook.com,Salesforce,salesforce.com,0,1,1,0,0,1,1,0
1,2,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.cisco@gmail.com,gmail.com,Cisco,cisco.com,0,1,0,0,0,1,1,1
2,3,Remote Job Offer – Data Scientist,We reviewed your profile and would like you to...,careers.google@gmail.com,gmail.com,Google,google.com,0,1,1,0,0,1,1,0
3,4,Invitation to Interview and Assessment – Data ...,Your application has been approved. Kindly pro...,recruiting.kpmg@outlook.com,outlook.com,KPMG,kpmg.com,0,1,0,0,0,1,1,1
4,5,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.tesla@secure-offer-letter.com,secure-offer-letter.com,Tesla,tesla.com,0,1,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Screening Call Request – Software Engineer,"Hi Sharath Nyalakonda, I'm a recruiter with Ro...",sourcer@roberthalf.com,roberthalf.com,Netflix,netflix.com,0,1,0,0,0,0,0,0
296,297,Client Interview Coordination – Machine Learni...,Thanks for your interest. As a staffing partne...,coordinator@teksystems.com,teksystems.com,Oracle,oracle.com,0,1,0,0,0,0,0,0
297,298,Recruiter Outreach (Agency) – AI Engineer,Thanks for your interest. As a staffing partne...,sourcer@roberthalf.com,roberthalf.com,Intel,intel.com,0,1,0,0,0,0,0,0
298,299,Recruiter Outreach (Agency) – Data Scientist,"Hi Sharath Nyalakonda, I'm a recruiter with Ap...",coordinator@apexsystems.com,apexsystems.com,Walmart,walmart.com,0,1,0,0,0,0,0,0
299,300,Talent Screening – Data Scientist,Thanks for your interest. As a staffing partne...,ta@adecco.com,adecco.com,LinkedIn,linkedin.com,0,1,0,0,0,0,0,0

In [68]:
df[df['label']==0]

,email_id,subject,body,sender_email,sender_domain,claimed_company,company_domain,domain_match,free_or_third_party_domain,has_link,has_attachment,mentions_money,mentions_urgency,mentions_personal_info,job_offer_without_interview,label
150,151,Interview Invitation – Software Engineer,Thank you for applying. Our team reviewed your...,hr@ibm.com,ibm.com,IBM,ibm.com,1,0,0,0,0,0,0,0,0
151,152,Interview Invitation – Data Scientist,"Following our review, we'd like to move forwar...",hr@deloitte.com,deloitte.com,Deloitte,deloitte.com,1,0,1,0,0,0,0,0,0
152,153,Next Steps – Data Scientist,We are currently reviewing applications. If se...,ta@jpmorgan.com,jpmorgan.com,JPMorgan Chase,jpmorgan.com,1,0,0,0,0,0,0,0,0
153,154,Thank you for applying – Business Analyst,We enjoyed reviewing your application. Next st...,jobs@lufthansagroup.com,lufthansagroup.com,Lufthansa Group,lufthansagroup.com,1,0,0,0,1,0,0,0,0
154,155,Application Update – Data Scientist,Thank you for applying. Our team reviewed your...,talent@jpmorgan.com,jpmorgan.com,JPMorgan Chase,jpmorgan.com,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Screening Call Request – Software Engineer,"Hi Sharath Nyalakonda, I'm a recruiter with Ro...",sourcer@roberthalf.com,roberthalf.com,Netflix,netflix.com,0,1,0,0,0,0,0,0,0
296,297,Client Interview Coordination – Machine Learni...,Thanks for your interest. As a staffing partne...,coordinator@teksystems.com,teksystems.com,Oracle,oracle.com,0,1,0,0,0,0,0,0,0
297,298,Recruiter Outreach (Agency) – AI Engineer,Thanks for your interest. As a staffing partne...,sourcer@roberthalf.com,roberthalf.com,Intel,intel.com,0,1,0,0,0,0,0,0,0
298,299,Recruiter Outreach (Agency) – Data Scientist,"Hi Sharath Nyalakonda, I'm a recruiter with Ap...",coordinator@apexsystems.com,apexsystems.com,Walmart,walmart.com,0,1,0,0,0,0,0,0,0
299,300,Talent Screening – Data Scientist,Thanks for your interest. As a staffing partne...,ta@adecco.com,adecco.com,LinkedIn,linkedin.com,0,1,0,0,0,0,0,0,0

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [70]:
v=TfidfVectorizer()

In [71]:
X_subject = v.fit_transform(df["subject"])

In [72]:
X_body=v.fit_transform(df['body'])

In [73]:
X_sender_email=v.fit_transform(df['sender_email'])

In [74]:
X_sender_domain=v.fit_transform(df['sender_domain'])

In [75]:
X_claimed_company=v.fit_transform(df['claimed_company'])

In [76]:
X_company_domain=v.fit_transform(df['company_domain'])

In [77]:
from sklearn.model_selection import train_test_split

In [85]:
df["subject_embedding"] = list(X_subject.toarray())
df["body_embedding"]=list(X_body.toarray())
df["sender_email_embedding"]=list(X_sender_email.toarray())
df["sender_domain_embedding"]=list(X_sender_domain.toarray())
df["claimed_company_embedding"]=list(X_claimed_company.toarray())
df["company_domain_emb"]=list(X_company_domain.toarray())

In [86]:
df.head()

,email_id,subject,body,sender_email,sender_domain,claimed_company,company_domain,domain_match,free_or_third_party_domain,has_link,...,mentions_urgency,mentions_personal_info,job_offer_without_interview,label,subject_embedding,body_embedding,sender_email_embedding,sender_domain_embedding,claimed_company_embedding,company_domain_emb
0,1,Remote Job Offer – Machine Learning Engineer,We reviewed your profile and would like you to...,careers.salesforce@outlook.com,outlook.com,Salesforce,salesforce.com,0,1,1,...,1,1,0,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.22329213007116525, 0.0, 0.0, 0.22...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.23066986..."
1,2,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.cisco@gmail.com,gmail.com,Cisco,cisco.com,0,1,0,...,1,1,1,1,"[0.0, 0.0, 0.0, 0.41298081102691103, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2878991515449...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9686031558031..."
2,3,Remote Job Offer – Data Scientist,We reviewed your profile and would like you to...,careers.google@gmail.com,gmail.com,Google,google.com,0,1,1,...,1,1,0,1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.22329213007116525, 0.0, 0.0, 0.22...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25262955..."
3,4,Invitation to Interview and Assessment – Data ...,Your application has been approved. Kindly pro...,recruiting.kpmg@outlook.com,outlook.com,KPMG,kpmg.com,0,1,0,...,1,1,1,1,"[0.0, 0.0, 0.0, 0.43311715805550466, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2878991515449...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.24443207..."
4,5,Invitation to Interview and Assessment – Cloud...,Your application has been approved. Kindly pro...,hrinfo.tesla@secure-offer-letter.com,secure-offer-letter.com,Tesla,tesla.com,0,1,0,...,1,1,1,1,"[0.0, 0.0, 0.0, 0.41298081102691103, 0.0, 0.0,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2878991515449...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.24861200..."

In [87]:
import numpy as np

X = np.hstack([
    np.vstack(df["subject_embedding"].to_numpy()),
    np.vstack(df["body_embedding"].to_numpy()),
    np.vstack(df["sender_email_embedding"].to_numpy()),
    np.vstack(df["sender_domain_embedding"].to_numpy()),
    np.vstack(df["claimed_company_embedding"].to_numpy()),
    np.vstack(df["company_domain_emb"].to_numpy()),
])

In [88]:
X_flags = df[
    [
        "domain_match",
        "free_or_third_party_domain",
        "has_link",
        "has_attachment",
        "mentions_money",
        "mentions_urgency",
        "mentions_personal_info",
        "job_offer_without_interview",
    ]
].astype("float32").to_numpy()

In [89]:
import numpy as np

X = np.hstack([
    np.vstack(df["subject_embedding"].to_numpy()),
    np.vstack(df["body_embedding"].to_numpy()),
    np.vstack(df["sender_email_embedding"].to_numpy()),
    np.vstack(df["sender_domain_embedding"].to_numpy()),
    np.vstack(df["claimed_company_embedding"].to_numpy()),
    np.vstack(df["company_domain_emb"].to_numpy()),
    X_flags
])

In [92]:
Y=df.label

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [96]:
len(X_train)

240

In [97]:
model=LogisticRegression()

In [98]:
model.fit(X_train,Y_train)

LogisticRegression()

In [101]:
Y_pred=model.predict(X_test)

In [102]:
from sklearn.metrics import classification_report

In [104]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00        27

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60

In [105]:
Y_pred

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1])

In [106]:
Y_test

24     1
65     1
113    1
261    0
188    0
181    0
59     1
87     1
293    0
277    0
244    0
43     1
193    0
284    0
238    0
26     1
245    0
214    0
189    0
281    0
52     1
215    0
130    1
64     1
164    0
70     1
138    1
202    0
230    0
132    1
47     1
151    0
25     1
183    0
197    0
298    0
276    0
98     1
231    0
76     1
129    1
167    0
270    0
100    1
191    0
199    0
139    1
106    1
36     1
10     1
273    0
111    1
286    0
119    1
280    0
195    0
237    0
80     1
172    0
56     1
Name: label, dtype: int64